services:
  playground:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |-
        python3 -m jupyter notebook --no-browser --allow-root --ip=0.0.0.0 --port=${JUPYTER_PORT}
    volumes:
      - C:\Data\Apps\research-assistant-backend:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ "gpu" ]