services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ${APP_PATH}:/app
      - ${CACHE_PATH}:/root/.cache
      - ${NLTK_DATA_PATH}:/root/nltk_data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ "gpu" ]
  playground:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"
    command:
      - python3
      - -m
      - jupyter
      - notebook
      - --no-browser
      - --allow-root
      - --ip=0.0.0.0
      - --port=${JUPYTER_PORT}
      - --NotebookApp.token=${JUPYTER_TOKEN}
    volumes:
      - ${APP_PATH}:/app
      - ${CACHE_PATH}:/root/.cache
      - ${NLTK_DATA_PATH}:/root/nltk_data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ "gpu" ]